steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/proud-stage-440012-c4/my-app', '.']
 
  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/proud-stage-440012-c4/my-app']


  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-app'
      - '--image'
      - 'gcr.io/proud-stage-440012-c4/my-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
 
timeout: '600s'
options:
  logging: CLOUD_LOGGING_ONLY
 
 
# Specify the substitutions (optional)
substitutions:
  _REGION: 'us-central1'
